
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.compiler.parser;

/** CUP generated class containing symbol constants. */
public class VSym {
  /* terminals */
  public static final int AS = 7;
  public static final int C_SEPARATOR = 5;
  public static final int DIVISION = 15;
  public static final int SCANF = 76;
  public static final int SQUAREBRACKETC = 20;
  public static final int SYSTEM = 81;
  public static final int CONST = 60;
  public static final int CHARTYPE = 74;
  public static final int NEXT = 45;
  public static final int P_SEPARATOR = 4;
  public static final int GREATEREQUALTHAN = 23;
  public static final int COMMA = 11;
  public static final int VB_SEPARATOR = 2;
  public static final int PARENTHESISO = 17;
  public static final int BYVAL = 38;
  public static final int INTEGER = 8;
  public static final int DOUBLE = 9;
  public static final int SUB = 37;
  public static final int VB_INCLUDE = 57;
  public static final int PARENTHESISC = 18;
  public static final int LOOP = 43;
  public static final int LITERAL = 86;
  public static final int OUT = 82;
  public static final int MULTIPLICATION = 14;
  public static final int NOT = 28;
  public static final int COMPARATION = 67;
  public static final int FLOAT = 63;
  public static final int THEN = 31;
  public static final int INTTYPE = 73;
  public static final int LESSEQUALTHAN = 22;
  public static final int GREATERTHAN = 25;
  public static final int CHARACTER = 89;
  public static final int PRINTLN = 84;
  public static final int FULLSTOP = 51;
  public static final int MOD = 16;
  public static final int CLASS = 80;
  public static final int J_INCLUDE = 87;
  public static final int INCLUDE = 56;
  public static final int SELECT = 39;
  public static final int CLRSCR = 78;
  public static final int LESSTHAN = 24;
  public static final int PRINTF = 68;
  public static final int WRITE = 53;
  public static final int J_INCLUDE_ALL = 59;
  public static final int PLUS = 12;
  public static final int WHILE = 41;
  public static final int CHAR = 10;
  public static final int GETCH = 79;
  public static final int FLOATTYPE = 75;
  public static final int SWITCH = 69;
  public static final int DO = 42;
  public static final int FOR = 44;
  public static final int VOID = 61;
  public static final int PUBLIC = 33;
  public static final int RETURN = 36;
  public static final int CONCAT = 55;
  public static final int ELSE = 32;
  public static final int FLOATINPUT = 49;
  public static final int BREAK = 72;
  public static final int AMPERSAND = 77;
  public static final int DIM = 6;
  public static final int INTEGERNUM = 88;
  public static final int EOF = 0;
  public static final int SEMICOLON = 66;
  public static final int DEFAULT = 70;
  public static final int PRINT = 83;
  public static final int FUNCTION = 34;
  public static final int CHARINPUT = 50;
  public static final int CONSOLE = 52;
  public static final int MAIN = 62;
  public static final int MINUS = 13;
  public static final int OR = 29;
  public static final int error = 1;
  public static final int PY_INCLUDE = 58;
  public static final int DOUBLENUM = 90;
  public static final int IF = 30;
  public static final int ID = 85;
  public static final int J_SEPARATOR = 3;
  public static final int CURLYBRACKETO = 64;
  public static final int END = 35;
  public static final int INTINPUT = 48;
  public static final int COLON = 71;
  public static final int WRITELINE = 54;
  public static final int CURLYBRACKETC = 65;
  public static final int NOTEQUAL = 26;
  public static final int CASE = 40;
  public static final int STEP = 47;
  public static final int AND = 27;
  public static final int TO = 46;
  public static final int EQUALS = 21;
  public static final int SQUAREBRACKETO = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VB_SEPARATOR",
  "J_SEPARATOR",
  "P_SEPARATOR",
  "C_SEPARATOR",
  "DIM",
  "AS",
  "INTEGER",
  "DOUBLE",
  "CHAR",
  "COMMA",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "MOD",
  "PARENTHESISO",
  "PARENTHESISC",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "EQUALS",
  "LESSEQUALTHAN",
  "GREATEREQUALTHAN",
  "LESSTHAN",
  "GREATERTHAN",
  "NOTEQUAL",
  "AND",
  "NOT",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "PUBLIC",
  "FUNCTION",
  "END",
  "RETURN",
  "SUB",
  "BYVAL",
  "SELECT",
  "CASE",
  "WHILE",
  "DO",
  "LOOP",
  "FOR",
  "NEXT",
  "TO",
  "STEP",
  "INTINPUT",
  "FLOATINPUT",
  "CHARINPUT",
  "FULLSTOP",
  "CONSOLE",
  "WRITE",
  "WRITELINE",
  "CONCAT",
  "INCLUDE",
  "VB_INCLUDE",
  "PY_INCLUDE",
  "J_INCLUDE_ALL",
  "CONST",
  "VOID",
  "MAIN",
  "FLOAT",
  "CURLYBRACKETO",
  "CURLYBRACKETC",
  "SEMICOLON",
  "COMPARATION",
  "PRINTF",
  "SWITCH",
  "DEFAULT",
  "COLON",
  "BREAK",
  "INTTYPE",
  "CHARTYPE",
  "FLOATTYPE",
  "SCANF",
  "AMPERSAND",
  "CLRSCR",
  "GETCH",
  "CLASS",
  "SYSTEM",
  "OUT",
  "PRINT",
  "PRINTLN",
  "ID",
  "LITERAL",
  "J_INCLUDE",
  "INTEGERNUM",
  "CHARACTER",
  "DOUBLENUM"
  };
}

