
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hluther.compiler.parser;

/** CUP generated class containing symbol constants. */
public class VSym {
  /* terminals */
  public static final int GREATERTHAN = 25;
  public static final int P_SEPARATOR = 4;
  public static final int SQUAREBRACKETO = 19;
  public static final int FUNCTION = 35;
  public static final int CHAR = 10;
  public static final int CONCAT = 56;
  public static final int EQUALS = 21;
  public static final int CASE = 41;
  public static final int SQUAREBRACKETC = 20;
  public static final int DOUBLE = 9;
  public static final int INTEGER = 8;
  public static final int NOTEQUAL = 26;
  public static final int PARENTHESISO = 17;
  public static final int FOR = 45;
  public static final int MINUS = 13;
  public static final int WRITE = 54;
  public static final int VB_SEPARATOR = 2;
  public static final int CHARACTER = 60;
  public static final int NOT = 28;
  public static final int AND = 27;
  public static final int ELSEIF = 33;
  public static final int PARENTHESISC = 18;
  public static final int DOUBLENUM = 61;
  public static final int LESSTHAN = 24;
  public static final int OR = 29;
  public static final int COMMA = 11;
  public static final int C_SEPARATOR = 5;
  public static final int INTINPUT = 49;
  public static final int SELECT = 40;
  public static final int J_SEPARATOR = 3;
  public static final int NEXT = 46;
  public static final int LOOP = 44;
  public static final int PLUS = 12;
  public static final int IF = 30;
  public static final int ID = 57;
  public static final int DIM = 6;
  public static final int EOF = 0;
  public static final int BYVAL = 39;
  public static final int RETURN = 37;
  public static final int GREATEREQUALTHAN = 23;
  public static final int error = 1;
  public static final int MOD = 16;
  public static final int LITERAL = 58;
  public static final int WRITELINE = 55;
  public static final int ELSE = 32;
  public static final int LESSEQUALTHAN = 22;
  public static final int FLOATINPUT = 50;
  public static final int TO = 47;
  public static final int WHILE = 42;
  public static final int PUBLIC = 34;
  public static final int THEN = 31;
  public static final int FULLSTOP = 52;
  public static final int CHARINPUT = 51;
  public static final int END = 36;
  public static final int AS = 7;
  public static final int DIVISION = 15;
  public static final int SUB = 38;
  public static final int MULTIPLICATION = 14;
  public static final int INTEGERNUM = 59;
  public static final int CONSOLE = 53;
  public static final int DO = 43;
  public static final int STEP = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VB_SEPARATOR",
  "J_SEPARATOR",
  "P_SEPARATOR",
  "C_SEPARATOR",
  "DIM",
  "AS",
  "INTEGER",
  "DOUBLE",
  "CHAR",
  "COMMA",
  "PLUS",
  "MINUS",
  "MULTIPLICATION",
  "DIVISION",
  "MOD",
  "PARENTHESISO",
  "PARENTHESISC",
  "SQUAREBRACKETO",
  "SQUAREBRACKETC",
  "EQUALS",
  "LESSEQUALTHAN",
  "GREATEREQUALTHAN",
  "LESSTHAN",
  "GREATERTHAN",
  "NOTEQUAL",
  "AND",
  "NOT",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "ELSEIF",
  "PUBLIC",
  "FUNCTION",
  "END",
  "RETURN",
  "SUB",
  "BYVAL",
  "SELECT",
  "CASE",
  "WHILE",
  "DO",
  "LOOP",
  "FOR",
  "NEXT",
  "TO",
  "STEP",
  "INTINPUT",
  "FLOATINPUT",
  "CHARINPUT",
  "FULLSTOP",
  "CONSOLE",
  "WRITE",
  "WRITELINE",
  "CONCAT",
  "ID",
  "LITERAL",
  "INTEGERNUM",
  "CHARACTER",
  "DOUBLENUM"
  };
}

